added morpheus as character
roannav/matrix-movies-website-hacktoberfest pull request #7
Opened 2023-10-02 20:12 UTC by Naman73598

Updated the character for Morpheus.
#hacktoberfest2023

2023-10-02 21:40 UTC, roannav commented on index.html
> +          <img src="/img/characters/Morpheus.jpg" alt="Morpheus" />
The photo file is named "morpheus.jpg", but the `<img>` tag is "Morpheus.jpg".  Please correct it to be lowercase in the `<img>` tag.

2023-10-02 21:44 UTC, roannav requested changes
The photo file is named "morpheus.jpg".  However, in index.html, the `<img>` tag is "Morpheus.jpg".  Please correct it to be lowercase in the `<img>` tag.

Then git add, git commit, and git push again.

2023-10-03 04:18 UTC, Naman73598 commented
Changes made . Please check @roannav

2023-10-03 05:55 UTC, roannav approved these changes

2023-10-03 05:56 UTC, merged

2023-10-03 05:57 UTC, roannav commented
@Naman73598  Thank you very much for your contribution! 🏆

2023-10-03 05:59 UTC, roannav commented
@all-contributors please add @Naman73598 for code and content